const products = [
	{
		id: 1,
		product: "Buket Snack Mix",
		price: 28000,
		desc: "Buket berisi kombinasi snack coklat dan wafer.",
		img: "bucket-snack.webp",
		type: "buket",
	},
	{
		id: 2,
		product: "Buket Boneka Karakter (Hitam)",
		price: 49000,
		desc: "Buket dengan boneka karakter wanita bergaun hitam.",
		img: "buket-boneka-1.webp",
		type: "buket",
	},
	{
		id: 3,
		product: "Buket Boneka Karakter (Pink)",
		price: 49000,
		desc: "Buket dengan boneka karakter wanita bergaun pink.",
		img: "buket-boneka-2.webp",
		type: "buket",
	},
	{
		id: 4,
		product: "Buket Bumbu Dapur (Twin)",
		price: 33000,
		desc: "Dua buket berisi rencengan bumbu masak sachet.",
		img: "buket-bumbu.webp",
		type: "buket",
	},
	{
		id: 5,
		product: "Buket Bumbu Dapur (Single)",
		price: 38000,
		desc: "Buket tunggal berisi bumbu masak sachet.",
		img: "buket-bumbu-2.webp",
		type: "buket",
	},
	{
		id: 6,
		product: "Buket Bunga Artificial (Pink)",
		price: 49000,
		desc: "Buket bunga hias berwarna merah muda.",
		img: "buket-bunga.webp",
		type: "buket",
	},
	{
		id: 7,
		product: "Buket Mawar Merah",
		price: 38000,
		desc: "Buket simpel dengan satu bunga mawar merah.",
		img: "buket-bunga-2.webp",
		type: "buket",
	},
	{
		id: 8,
		product: "Buket Sabun Batang",
		price: 27000,
		desc: "Buket unik berisi sabun mandi batang.",
		img: "buket-sabun.webp",
		type: "buket",
	},
	{
		id: 9,
		product: "Buket Sabun & Kopi",
		price: 49000,
		desc: "Kombinasi sabun mandi dan kopi sachet.",
		img: "buket-sabun-kopi.webp",
		type: "buket",
	},
	{
		id: 10,
		product: "Buket Snack & Kopi",
		price: 25000,
		desc: "Kombinasi snack ringan dengan kopi instan.",
		img: "buket-snack-kopi.webp",
		type: "buket",
	},
	{
		id: 11,
		product: "Buket Snack & Uang",
		price: 28000,
		desc: "Buket snack yang diselipkan lembaran uang tunai.",
		img: "buket-snack-uang.webp",
		type: "buket",
	},
	{
		id: 12,
		product: "Money Bouquet (Kipas Uang)",
		price: 135000,
		desc: "Buket yang dirangkai full dari lembaran uang tunai.",
		img: "buket-uang.webp",
		type: "buket",
	},
];

export default products;
